### ISSUE TITLE
[META] Firefox Engineering Review

### ISSUE THREAD

**Issue by biancadanforth** [citp/news-disinformation-study#33]
## Engineering Review Checklist for Firefox WebExtension Experiments
This is a working checklist for reviewing WebExtension experiments in Firefox. Items may be added, edited or removed at any time.

- [ ] `README`:
  - [ ] Explains clearly what the extension does for each experimental branch and control.
  - [ ] Lists any extension configuration settings useful for testing.
  - [ ] Links out to a META bug and/or other documents with more context, including what Firefox channel and version the experiment is targeted for.
- [ ] `manifest.json` contains the following fields:
  - [ ] `name`
  - [ ] `version`
  - [ ] `author`
  - [ ] `description`
  - [ ] `homepage_url`
  - [ ] `incognito` (recommended value: `"not_allowed"`)
  - [ ] `hidden` (value: `true`)
  - [ ] `applications.gecko.id` (typically of the form `"study-name@mozilla.org"`)
  - [ ] `applications.gecko.strict_min_version` (preferable)
  - [ ] `applications.gecko.strict_max_version` (preferable)
- [ ] Extension [follows guidelines for modifying Firefox Prefs](https://docs.telemetry.mozilla.org/cookbooks/client_guidelines.html#prefs).
- [ ] WE API engineers confirm that the extension's use of WE APIs (public, privileged or experimental) will not trigger known bugs.
- [ ] Extension [does not cause feature regressions in Try server tests](https://docs.telemetry.mozilla.org/cookbooks/client_guidelines.html#testing-extensions).
- [ ] Extension does not cause significant[1] performance regressions.
- [ ] Only source files used by the extension are included in the XPI.
- [ ] Additional reviews (e.g. data, legal, privacy, security, ...) may be required if:
  - [ ] The extension makes use of third party libraries and/or services.
  - [ ] The extension modifies web page content in any way.
  - [ ] Data is transmitted outside of Mozilla's telemetry pipeline.

[1]: As a reference, for a production application (i.e. not an experiment), a 2-3% worst case scenario regression in page load time would generally be considered acceptable. Since experiments are temporary and typically only go out to a very small percentage of users, we can often be more lenient.

**Comment by jonathanmayer** [comment]
Closing this out, since the (exceedingly helpful) review was of a study version that's now over a year old.
